name: "Build wrapper"

on:
    push:
        paths:
            - scripts/**
    workflow_dispatch:

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]

        permissions:
            contents: read
            
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.11
              uses: actions/setup-python@v4
              with:
                python-version: "3.11"
                
            - name: Install pip packages
              run: python -m pip install -U setuptools pyserial nuitka

            # TODO: combine with the windows one
            - name: Compile wrapper binary (Non-Windows)
              # currently only amd64 runners are available
              if: matrix.os != 'windows-latest'
              run: |
                cd scripts
                if [[ "${{ matrix.os }}" == 'macos-latest' ]]; then
                  output_suffix="macOS_amd64"
                else
                  output_suffix="linux_amd64"
                fi
                python -m nuitka --standalone --assume-yes-for-downloads -o "wrapper_${output_suffix}.bin" wrapper.py
                mv wrapper.dist wrapper_${output_suffix}

            - name: Compile wrapper binary (Windows)
              # currently only amd64 runners are available
              if: matrix.os == 'windows-latest'
              run: |
                cd scripts
                python -m nuitka --standalone --assume-yes-for-downloads -o wrapper_${{ matrix.os }}_amd64.exe wrapper.py

            # upload wrapper_*.bin
            - uses: actions/upload-artifact@v3
              if: matrix.os != 'windows-latest'
              with:
                name: wrapper_${output_suffix}
                path: ./scripts/wrapper_${output_suffix}

            - uses: actions/upload-artifact@v3
              if: matrix.os == 'windows-latest'
              with:
                name: wrapper_win32
                path: ./scripts/wrapper_win32
