name: "Build wrapper"

on:
    push:
        paths:
            - scripts/**

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]

        permissions:
            contents: read
            
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.11
              uses: actions/setup-python@v4
              with:
                python-version: "3.11"
                
            - name: Install pip packages
              run: python -m pip install -U setuptools pyserial nuitka
            - name: Compile wrapper binary
              # currently only amd64 runners are available
              run: |
                cd pyboard-serial-com
                python -m nuitka --standalone --onefile -o wrapper_${{ matrix.os }}_amd64.bin wrapper.py

            # upload wrapper_*.bin
            - uses: actions/upload-artifact@v3
              with:
                name: wrapper_${{ matrix.os }}_amd64.bin
                path: ./wrapper_${{ matrix.os }}_amd64.bin
